DROP DATABASE IF EXISTS idlebattle;
CREATE DATABASE IF NOT EXISTS idlebattle;

use idlebattle;

CREATE TABLE IF NOT EXISTS User (
  idUser VARCHAR(36) NOT NULL,
  typeUser SMALLINT(1) NOT NULL,
  email VARCHAR(320),
  hashedPassword VARCHAR(128),
  salt VARCHAR(12),
  PRIMARY KEY (idUser)
);

CREATE TABLE IF NOT EXISTS Hero (
  idHero CHAR(36) NOT NULL,
  firstName VARCHAR(30) NOT NULL,
  rankLvl TINYINT(255) UNSIGNED NOT NULL,
  skillPoint TINYINT(255) UNSIGNED NOT NULL,
  health TINYINT(255) UNSIGNED NOT NULL,
  attack TINYINT(255) UNSIGNED NOT NULL, 
  defense TINYINT(255) UNSIGNED NOT NULL,
  magik TINYINT(255) UNSIGNED NOT NULL,
  idUser VARCHAR(10) NOT NULL,
  FOREIGN KEY(idUser) REFERENCES User(idUser),
  PRIMARY KEY (idHero)
);

CREATE TABLE IF NOT EXISTS Fight (
  idFight CHAR(36) NOT NULL,
  idHero CHAR(36) NOT NULL,
  opponentName VARCHAR(30) NOT NULL,
  result SMALLINT(1) NOT NULL,
  dateFight DATETIME NOT NULL,
  report VARCHAR(2000),
  FOREIGN KEY(idHero) REFERENCES Hero(idHero),
  PRIMARY KEY (idFight)
);
