DROP DATABASE IF EXISTS idlebattle;
CREATE DATABASE IF NOT EXISTS idlebattle;

use idlebattle;

CREATE TABLE IF NOT EXISTS User (
  idUser CHAR(36) NOT NULL,
  typeUser SMALLINT(1) NOT NULL,
  email VARCHAR(320),
  hashedPassword VARCHAR(128),
  salt VARCHAR(12),
  PRIMARY KEY (idUser),
  UNIQUE KEY (email)
);

CREATE TABLE IF NOT EXISTS Hero (
  idHero CHAR(36) NOT NULL,
  firstName VARCHAR(30) NOT NULL,
  rankLvl TINYINT(255) UNSIGNED NOT NULL,
  skillPoint TINYINT(255) UNSIGNED NOT NULL,
  health TINYINT(255) UNSIGNED NOT NULL,
  attack TINYINT(255) UNSIGNED NOT NULL, 
  defense TINYINT(255) UNSIGNED NOT NULL,
  magik TINYINT(255) UNSIGNED NOT NULL,
  idUser VARCHAR(36) NOT NULL,
  FOREIGN KEY(idUser) REFERENCES User(idUser),
  PRIMARY KEY (idHero)
);

CREATE TABLE IF NOT EXISTS Fight (
  idFight CHAR(36) NOT NULL,
  idHero CHAR(36) NOT NULL,
  opponentName VARCHAR(30) NOT NULL,
  result SMALLINT(1) NOT NULL,
  dateFight DATETIME NOT NULL,
  FOREIGN KEY(idHero) REFERENCES Hero(idHero) ON DELETE CASCADE,
  PRIMARY KEY (idFight)
);

CREATE TABLE IF NOT EXISTS Turn (
  idTurn CHAR(36) NOT NULL,
  turnNumber TINYINT(255) UNSIGNED NOT NULL,
  attackHeroA TINYINT(255) UNSIGNED NOT NULL,
  loosedHealthHeroB TINYINT(255) UNSIGNED NOT NULL,
  attackHeroB TINYINT(255) UNSIGNED,
  loosedHealthHeroA TINYINT(255) UNSIGNED,
  idFight CHAR(36) NOT NULL,
  FOREIGN KEY(idFight) REFERENCES Fight(idFight) ON DELETE CASCADE,
  PRIMARY KEY (idTurn)
);